-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 01:06:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testdb` ;

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`chuyennganh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`chuyennganh` ;

CREATE TABLE IF NOT EXISTS `testdb`.`chuyennganh` (
  `MaCN` VARCHAR(10) NOT NULL,
  `TenCN` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MaCN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`user` ;

CREATE TABLE IF NOT EXISTS `testdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `permissions` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_sb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`giaovien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`giaovien` ;

CREATE TABLE IF NOT EXISTS `testdb`.`giaovien` (
  `MaGV` VARCHAR(6) NOT NULL,
  `TenGV` VARCHAR(50) NULL DEFAULT NULL,
  `Diachi` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `DienThoai` VARCHAR(10) NULL DEFAULT NULL,
  `CMND` VARCHAR(12) NULL DEFAULT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `roleid` INT NULL DEFAULT NULL,
  `GioiTinh` VARCHAR(4) NULL DEFAULT NULL,
  `MaCN` VARCHAR(10) NULL DEFAULT NULL,
  `GVCN` VARCHAR(10) NULL DEFAULT NULL,
  `TrangThai` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`MaGV`),
  INDEX `FK_ChuyenNganh_GiaoVien` (`MaCN` ASC) VISIBLE,
  INDEX `fk_giaovien_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_ChuyenNganh_GiaoVien`
    FOREIGN KEY (`MaCN`)
    REFERENCES `testdb`.`chuyennganh` (`MaCN`),
  CONSTRAINT `fk_giaovien_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`monhoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`monhoc` ;

CREATE TABLE IF NOT EXISTS `testdb`.`monhoc` (
  `MaMon` VARCHAR(6) NOT NULL,
  `TenMon` VARCHAR(20) NULL DEFAULT NULL,
  `SoTC` INT NULL DEFAULT NULL,
  `MaCN` VARCHAR(10) NULL DEFAULT NULL,
  `Ca` VARCHAR(5) NULL DEFAULT NULL,
  `Thu` VARCHAR(10) NULL DEFAULT NULL,
  `NgayThi` DATE NULL DEFAULT NULL,
  `CaThi` VARCHAR(5) NULL DEFAULT NULL,
  `GiaTien` INT NULL DEFAULT NULL,
  PRIMARY KEY (`MaMon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`giaovien_monhoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`giaovien_monhoc` ;

CREATE TABLE IF NOT EXISTS `testdb`.`giaovien_monhoc` (
  `MaGV` VARCHAR(6) NULL DEFAULT NULL,
  `MaMon` VARCHAR(6) NULL DEFAULT NULL,
  INDEX `FK_GiaoVien_MonHoc_MonHoc` (`MaMon` ASC) VISIBLE,
  INDEX `FK_GiaoVien_MonHoc_Giaovien` (`MaGV` ASC) VISIBLE,
  CONSTRAINT `FK_GiaoVien_MonHoc_Giaovien`
    FOREIGN KEY (`MaGV`)
    REFERENCES `testdb`.`giaovien` (`MaGV`),
  CONSTRAINT `FK_GiaoVien_MonHoc_MonHoc`
    FOREIGN KEY (`MaMon`)
    REFERENCES `testdb`.`monhoc` (`MaMon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`lop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`lop` ;

CREATE TABLE IF NOT EXISTS `testdb`.`lop` (
  `MaLop` VARCHAR(6) NOT NULL,
  `TenLop` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`MaLop`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`sinhvien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`sinhvien` ;

CREATE TABLE IF NOT EXISTS `testdb`.`sinhvien` (
  `MaSV` VARCHAR(6) NOT NULL,
  `TenSV` VARCHAR(50) NULL DEFAULT NULL,
  `Diachi` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `DienThoai` VARCHAR(10) NULL DEFAULT NULL,
  `CMND` VARCHAR(12) NOT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `roleid` INT NULL DEFAULT NULL,
  `GioiTinh` VARCHAR(4) NULL DEFAULT NULL,
  `MaCN` VARCHAR(10) NULL DEFAULT NULL,
  `GVCN` VARCHAR(10) NOT NULL,
  `TrangThai` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`MaSV`),
  UNIQUE INDEX `MaSV_UNIQUE` (`MaSV` ASC) VISIBLE,
  UNIQUE INDEX `CMND_UNIQUE` (`CMND` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `DienThoai_UNIQUE` (`DienThoai` ASC) VISIBLE,
  INDEX `FK_ChuyenNganh_SinhVien` (`MaCN` ASC) INVISIBLE,
  INDEX `fk_sinhvien_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_ChuyenNganh_SinhVien`
    FOREIGN KEY (`MaCN`)
    REFERENCES `testdb`.`chuyennganh` (`MaCN`),
  CONSTRAINT `fk_sinhvien_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`giaovien_sinhvien_lop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`giaovien_sinhvien_lop` ;

CREATE TABLE IF NOT EXISTS `testdb`.`giaovien_sinhvien_lop` (
  `MaGV` VARCHAR(6) NOT NULL,
  `MaMon` VARCHAR(6) NULL DEFAULT NULL,
  `MaLop` VARCHAR(6) NULL DEFAULT NULL,
  `MaSV` VARCHAR(6) NULL DEFAULT NULL,
  `TrangThai` INT NULL DEFAULT NULL,
  PRIMARY KEY (`MaGV`),
  INDEX `GiaoVien_SinhVien_Lop_SinhVien` (`MaSV` ASC) VISIBLE,
  INDEX `GiaoVien_SinhVien_Lop_Lop` (`MaLop` ASC) VISIBLE,
  CONSTRAINT `GiaoVien_SinhVien_Lop_GiaoVien`
    FOREIGN KEY (`MaGV`)
    REFERENCES `testdb`.`giaovien` (`MaGV`),
  CONSTRAINT `GiaoVien_SinhVien_Lop_Lop`
    FOREIGN KEY (`MaLop`)
    REFERENCES `testdb`.`lop` (`MaLop`),
  CONSTRAINT `GiaoVien_SinhVien_Lop_SinhVien`
    FOREIGN KEY (`MaSV`)
    REFERENCES `testdb`.`sinhvien` (`MaSV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`lichdangkyhoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`lichdangkyhoc` ;

CREATE TABLE IF NOT EXISTS `testdb`.`lichdangkyhoc` (
  `MaMon` VARCHAR(6) NOT NULL,
  `NgayBatDau` DATETIME NULL DEFAULT NULL,
  `NgayKetThuc` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`MaMon`),
  CONSTRAINT `FK_LichDangKyHoc_MonHoc`
    FOREIGN KEY (`MaMon`)
    REFERENCES `testdb`.`monhoc` (`MaMon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`lop_chunhiem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`lop_chunhiem` ;

CREATE TABLE IF NOT EXISTS `testdb`.`lop_chunhiem` (
  `MaLop` VARCHAR(6) NULL DEFAULT NULL,
  `TenLop` VARCHAR(20) NULL DEFAULT NULL,
  `MaCN` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `FK_Lop_ChuNhiem_ChuyenNganh` (`MaCN` ASC) VISIBLE,
  INDEX `FK_SinhVien_Diem` (`MaLop` ASC) VISIBLE,
  CONSTRAINT `FK_Lop_ChuNhiem_ChuyenNganh`
    FOREIGN KEY (`MaCN`)
    REFERENCES `testdb`.`chuyennganh` (`MaCN`),
  CONSTRAINT `FK_SinhVien_Diem`
    FOREIGN KEY (`MaLop`)
    REFERENCES `testdb`.`lop` (`MaLop`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`sinhvien_diem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`sinhvien_diem` ;

CREATE TABLE IF NOT EXISTS `testdb`.`sinhvien_diem` (
  `MaSV` VARCHAR(6) NULL DEFAULT NULL,
  `MaMon` VARCHAR(6) NULL DEFAULT NULL,
  `DiemQuaTrinh` INT NULL DEFAULT NULL,
  `DiemCuoiKy` INT NULL DEFAULT NULL,
  `DiemTongke` INT NULL DEFAULT NULL,
  INDEX `FK_SinhVien_Diem_MonHoc` (`MaMon` ASC) VISIBLE,
  INDEX `FK_SinhVien_Diem_SinhVien` (`MaSV` ASC) VISIBLE,
  CONSTRAINT `FK_SinhVien_Diem_MonHoc`
    FOREIGN KEY (`MaMon`)
    REFERENCES `testdb`.`monhoc` (`MaMon`),
  CONSTRAINT `FK_SinhVien_Diem_SinhVien`
    FOREIGN KEY (`MaSV`)
    REFERENCES `testdb`.`sinhvien` (`MaSV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
